# Generated by Django 3.2.9 on 2021-11-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_auto_20211114_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerInfo',
            new_name='CustomerOrder',
        ),
    ]
